import type { BlockDef } from "../types.js";

export const LOOKS: BlockDef[] = [
  { signature: "change [EFFECT v] effect by (CHANGE)", opcode: "looks_changeeffectby", shape: "stack",
    inputs: { CHANGE: { kind: "number", shadowType: 4 } },
    fields: { EFFECT: { kind: "dropdown", options: ["color", "fisheye", "whirl", "pixelate", "mosaic", "brightness", "ghost"] } } },
  { signature: "set [EFFECT v] effect to (VALUE)", opcode: "looks_seteffectto", shape: "stack",
    inputs: { VALUE: { kind: "number", shadowType: 4 } },
    fields: { EFFECT: { kind: "dropdown", options: ["color", "fisheye", "whirl", "pixelate", "mosaic", "brightness", "ghost"] } } },
  { signature: "say (MESSAGE) for (SECS) seconds", opcode: "looks_sayforsecs", shape: "stack", inputs: { MESSAGE: { kind: "text", shadowType: 10 }, SECS: { kind: "number", shadowType: 4 } } },
  { signature: "say (MESSAGE)", opcode: "looks_say", shape: "stack", inputs: { MESSAGE: { kind: "text", shadowType: 10 } } },
  { signature: "think (MESSAGE) for (SECS) seconds", opcode: "looks_thinkforsecs", shape: "stack", inputs: { MESSAGE: { kind: "text", shadowType: 10 }, SECS: { kind: "number", shadowType: 4 } } },
  { signature: "think (MESSAGE)", opcode: "looks_think", shape: "stack", inputs: { MESSAGE: { kind: "text", shadowType: 10 } } },
  { signature: "switch costume to [COSTUME v]", opcode: "looks_switchcostumeto", shape: "stack", inputs: { COSTUME: { kind: "menu", menuOpcode: "looks_costume", field: "COSTUME", default: "costume1" } } },
  { signature: "next costume", opcode: "looks_nextcostume", shape: "stack" },
  { signature: "switch backdrop to [BACKDROP v]", opcode: "looks_switchbackdropto", shape: "stack", inputs: { BACKDROP: { kind: "menu", menuOpcode: "looks_backdrops", field: "BACKDROP", default: "backdrop1" } } },
  { signature: "switch backdrop to [BACKDROP v] and wait", opcode: "looks_switchbackdroptoandwait", shape: "stack", inputs: { BACKDROP: { kind: "menu", menuOpcode: "looks_backdrops", field: "BACKDROP", default: "backdrop1" } } },
  { signature: "next backdrop", opcode: "looks_nextbackdrop", shape: "stack" },
  { signature: "clear graphic effects", opcode: "looks_cleargraphiceffects", shape: "stack" },
  { signature: "change size by (CHANGE)", opcode: "looks_changesizeby", shape: "stack", inputs: { CHANGE: { kind: "number", shadowType: 4 } } },
  { signature: "set size to (SIZE) %", opcode: "looks_setsizeto", shape: "stack", inputs: { SIZE: { kind: "number", shadowType: 4 } } },
  { signature: "show", opcode: "looks_show", shape: "stack" },
  { signature: "hide", opcode: "looks_hide", shape: "stack" },
  { signature: "go to [FRONT_BACK v] layer", opcode: "looks_gotofrontback", shape: "stack", fields: { FRONT_BACK: { kind: "dropdown" } } },
  { signature: "go [FORWARD_BACKWARD v] (NUM) layers", opcode: "looks_goforwardbackwardlayers", shape: "stack", inputs: { NUM: { kind: "number", shadowType: 7 } }, fields: { FORWARD_BACKWARD: { kind: "dropdown" } } },
  { signature: "costume [NUMBER_NAME v]", opcode: "looks_costumenumbername", shape: "reporter", fields: { NUMBER_NAME: { kind: "dropdown" } } },
  { signature: "backdrop [NUMBER_NAME v]", opcode: "looks_backdropnumbername", shape: "reporter", fields: { NUMBER_NAME: { kind: "dropdown" } } },
  { signature: "size", opcode: "looks_size", shape: "reporter" },
];
